version: '3'
services:
  db:
    image: postgres:14.3
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sasa
      - POSTGRES_DB=msvc_courses
    restart: always
    container_name: msvc-course-db